# Site settings
title: 同志社大学 社会情報学研究室
email:
description: 同志社大学 社会情報学研究室（下原勝憲・Ivan Tanev研究室）のWebサイトです。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sil.doshisha.ac.jp" # the base hostname & protocol for your site
github_username:  sil-doshisha

# Build settings
markdown: kramdown
